---
- hosts: dev
  become: yes
  remote_user: ec2-user

  tasks:
    - name: Update S3 code bucket
      s3_sync:
        region: us-west-2
        bucket: "{{ s3code }}"
        delete: True
        file_root: /var/www/html/

    - name: Append WP_SITEURL to wp config
      lineinfile:
        regexp: "^define[(]'WP_SITEURL'"
        line: "define('WP_SITEURL','http://dev.{{ domain }}.com');"
        path: "/var/www/html/wp-config.php"
        create: True
        state: present

    - name: Append WP_HOME to wp config
      lineinfile:
        regexp: "^define[(]'WP_HOME'"
        line: "define('WP_HOME','http://dev.{{ domain }}.com');"
        path: "/var/www/html/wp-config.php"
        state: present
