---
- hosts: dev
  become: yes
  remote_user: ec2-user

  vars:
    - apache_packages:
        - httpd
        - php
        - php-mysql

  tasks:
    - name: Install apache
      yum:
        name: "{{ apache_packages }}"
        state: present

    - name: Download Wordpress
      get_url:
        url: http://wordpress.org/wordpress-latest.tar.gz
        dest: /var/www/html/wordpress.tar.gz
        force: yes

    - name: Extract Wordpress
      unarchive:
        remote_src: True
        src: /var/www/html/wordpress.tar.gz
        dest: /var/www/html
        extra_opts:
          - "--strip-components=1"

    - name: Make my directory tree readable
      file:
        path: /var/www/html/
        mode: "u=rwX,g=rX,o=rX"
        recurse: yes
        owner: apache
        group: apache

    - name: Make sure Apache is started now and at bood
      service:
        name: httpd
        state: started
        enabled: True
